sonar.projectKey=fleetops-vehicle-service
sonar.projectName=fleetops-vehicle-service
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/target/**,**/build/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*
sonar.cpd.exclusions=**/*
